apiVersion: v1
kind: Secret
metadata:
  name: uai-robot-secrets
  namespace: uai-robot
type: Opaque
stringData:
  API_TOKEN: "CHANGE_ME"
  ADMIN_ID: "0"
  PASSWORD_ADMIN: "Admin"
  OPENAI_API_KEY: "sk-CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME"
  WEBHOOK_SECRET: "CHANGE_ME"
  ROBOKASSA_LOGIN: ""
  ROBOKASSA_PASS1: ""
  ROBOKASSA_PASS2: ""
  YOOKASSA_ACCOUNT_ID: ""
  YOOKASSA_SECRET_KEY: ""
